services:
    api:
        image: ghcr.io/engineer-man/piston
        container_name: piston_api
        privileged: true
        restart: unless-stopped
        ports:
            - "127.0.0.1:2000:2000"
        volumes:
            - piston_data:/piston/packages
        tmpfs:
            - /tmp:exec
        environment:
            - PISTON_RUN_TIMEOUT=30000
            - PISTON_COMPILE_TIMEOUT=60000
        networks:
            - piston
    
    frontend:
        image: quest-frontend-testing-image-2
        build:
            context: ./frontend
            dockerfile: Dockerfile 
        container_name: quest_frontend
        restart: unless-stopped
        ports:
            - "3000:3000"
        env_file:
            - ./frontend/.env
        depends_on:
            - backend
        networks:
            - quest


    backend:
        image: quest-backend
        build:
            context: .
            dockerfile: ./backend/Dockerfile 
        container_name: quest_backend
        restart: always
        ports:
            - "127.0.0.1:4000:4000"
        env_file:
            - ./backend/.env
        networks:
            - quest
            - mongo-data-network
            - piston
        
    mongo:
        image: mongo
        container_name: mongo
        env_file:
            - ./.env.mongo
        ports:
          - "0.0.0.0:27017:27017"
        volumes:
          - quest-data:/data/db 
        networks:
          - n8n_network
          - mongo-data-network
          - expense-tracker
    
    mongo-express:
        image: mongo-express
        container_name: quest_mongo_express
        profiles:
            - quest-express
        ports:
            - "127.0.0.1:8081:8081"
        
        env_file:
            - ./.env.mongo-express
        depends_on:
            - mongo
        networks:
            - mongo-data-network
            - expense-tracker


volumes:
    piston_data:
    quest-data:

networks:
    n8n_network:
        external: true
    quest:
        external: true
    mongo-data-network:
        external: true
    piston:
    expense-tracker:
        external: true